<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My First Game</title>
</head>
<body>
    <h2>MY FIRST GAME</h2>
    <p>Welcome ! In this game, you need to be the fastest.</p>
    <p>You have 3 rounds to complete :</p>
    <ul>
        <li>Guess a number generated by the computer the fastest</li>
        <li>Remember as many words as possible in seconds</li>
        <li>Resolve 3 simple calculations as fast as possible</li>
    </ul>
    <h3>FIRST ROUND</h3>
    <p>GUESS A NUMBER</p>
    <p>The number to guess is between 0 and 100 included</p>
    <?php
    include 'functions.php';
    session_start();

    if (!isset($_SESSION['theNbToFind'])) {
        // If the session variable doesn't exist, generate a new nb to guess et store it in the session variable
        $_SESSION['theNbToFind'] = generateNb();
    }

    echo "The number to guess is: ".$_SESSION['theNbToFind'];
    echo '<form method="post" action="">';
    echo '<input type="text" autofocus name="text" id="text">';
    echo '<input type="submit" value="Enter">';
    echo '<span id="clue">';
    if (!empty($_POST["text"])) echo findTheNb($_POST["text"], $_SESSION['theNbToFind']);
    echo '</span>'; //says "more" or "less"
    ?>
    </form>
     
    <!-- <p id="found-nb"></p> sentence which says the number is found -->
</body>
</html>