<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My First Game</title>

    <style>
        table, td {
        border: 1px solid;
        }

        td {
            width:80px;
        }
    </style>
</head>
<body>
    <h2>MY FIRST GAME</h2>
    <p>Welcome ! In this game, you need to be the fastest.</p>
    <p>You have 3 rounds to complete :</p>
    <ul>
        <li>Guess a number generated by the computer the fastest</li>
        <li>Remember as many words as possible in seconds</li>
        <li>Resolve 3 simple calculations as fast as possible</li>
    </ul>
    <h3>FIRST ROUND</h3>
    <p>GUESS A NUMBER</p>
    <p>The number to guess is between 0 and 100 included</p>
    <?php
    include 'functions.php';
    session_start();

    if (!isset($_SESSION['theNbToFind'])) {
        // If the session variable doesn't exist, generate a new nb to guess et store it in the session variable
        $_SESSION['theNbToFind'] = generateNb();
    }

    echo "The number to guess is: ".$_SESSION['theNbToFind'];
    echo '<form method="post" action="">';
    echo '<input type="text" autofocus name="text" id="text">';
    echo '<input type="submit" value="Enter">';
    echo '<span id="clue">';
    if (!empty($_POST["text"])) echo findTheNb($_POST["text"], $_SESSION['theNbToFind']);
    echo '</span>'; //says "more" or "less"
    ?>
    </form>

    <br>
    <br>
    <h3>SECOND ROUND</h3>
    <p>MEMORIZE ALL THE WORDS</p>
    <?php
    $seconds = 10;
    echo '<p>You have '.$seconds.' seconds to memorize all the words you can</p>';
    echo '<form method="post" action="">';
    echo '<p>Are you ready ? Press the button !';
    echo '<input type="submit" value="Ready" id="submit_button">';
    echo '</form>';

    // timer
    if(isset($_POST['submit_button'])){
    $start_time = time();
    $end_time = $start_time + $seconds;
    $wordsArray = ["dog", "potatoe", "shoe", "garlic","cheese", "pancake", "car", "chocolate", "taxi", "basketball", "match", "blue", "moon", "water"];

    while (time() < $end_time) {
        $remaining_time = $end_time - time();
        echo '<span id="spanId">'.$remaining_time.'</span>';
        if (time() == $start_time) {
            echo '<table id="tableId"><tr>';
            for ($i = 0; $i < 7; $i++)
            {
                echo '<td>'.$wordsArray[$i].'</td>';
            }
            echo '</tr><tr>';
            for ($i = 0; $i < 7; $i++)
            {
                echo '<td>'.$wordsArray[$i+7].'</td>';
            }
            echo '</tr></table>';
        }
        ob_flush();
        flush();
        sleep(1); // pause de 1 seconde entre chaque itération
        echo "<script>document.getElementById('spanId').remove();</script>";

    }
    if (time() == $end_time) {
        echo "<script>document.getElementById('tableId').remove();</script>";
    }

    }
    
    
    echo 'Time up! Write all the words you think you memorize.';
    echo '<br>Write each word, one by one.';
    $wordsYouFoundArray = [];
    echo '<form>';
    echo '<input type="text">';
    echo '<input type="submit" value="submit" name="word-found">';
    array_push($wordsYouFoundArray, $_POST["word-found"]);
    echo '</form>';
    for ($i = 0; $i < count($wordsYouFoundArray); $i++) {
        echo $wordsYouFoundArray[$i];
    }
   
    ?>
     
</body>
</html>