<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My First Game</title>
</head>
<body>
    <h2>MY FIRST GAME</h2>
    <p>Welcome ! In this game, you need to be the fastest.</p>
    <p>You have 3 rounds to complete :</p>
    <ul>
        <li>Guess a number generated by the computer the fastest</li>
        <li>Remember as many words as possible in seconds</li>
        <li>Resolve 3 simple calculations as fast as possible</li>
    </ul>
    <h3>FIRST ROUND</h3>
    <p>GUESS A NUMBER</p>
    <form method="post" action="functions.php">
    <input type="text" name="text" id="text">
    <input type="submit" value="Enter">
    </form>
    <span id="clue"><?php if (1==1) echo 'hello';?></span> <!-- says "more" or "less" -->
    <p id="found-nb"></p> <!-- sentence which says the number is found -->
</body>
</html>