<?php
session_start();

include 'functions.php';

if (isset($_POST["pseudo"])) {
    // If the previous page return a pseudo -> session variable = pseudo
    $_SESSION["myPseudo"] = $_POST["pseudo"];
}

if (!isset($_SESSION['theNbToFind'])) {
    // If the session variable doesn't exist, generate a new nb to guess et store it in the session variable
    $_SESSION['theNbToFind'] = generateNb();
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My First Game</title>
</head>
<body>
    <?php
        echo 'Welcome '.$_SESSION["myPseudo"].' in My First Game !';
    ?>
    <p>In this game, you need to be the fastest.</p>
    <p>You have 3 rounds to complete :</p>
    <ul>
        <li>Guess a number generated by the computer the fastest</li>
        <li>Remember as many words as possible in seconds</li>
        <li>Resolve 3 simple calculations as fast as possible</li>
    </ul>
    <h3>FIRST ROUND</h3>
    <p>GUESS A NUMBER</p>
    <p>The number to guess is between 0 and 100 included</p>
    <?php 
        echo "The number to guess is: ".$_SESSION['theNbToFind'];
    ?>
    <form method="post" action="">
    <input type="text" autofocus name="nb">
    <input type="submit" value="Enter">
    <!-- the span says "more" or "less" or "nb found" -->
    <span id="clue">
        <?php if (!empty($_POST["nb"])) echo findTheNb($_POST["nb"], $_SESSION['theNbToFind']);?>
    </span> 
    </form>
    <form action="round2.php"><input type="submit" value="Next Round"></form>
 </body>
 </html>