<?php
session_start();

if (isset($_POST["pseudo"])) {
    // If the previous page return a pseudo -> session variable = pseudo
    $_SESSION["myPseudo"] = $_POST["pseudo"];
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My First Game</title>
</head>
<body>
    <?php
        echo 'Welcome '.$_SESSION["myPseudo"].' in My First Game !';
    ?>
    <p>In this game, you need to be the fastest.</p>
    <p>You have 3 rounds to complete :</p>
    <ul>
        <li>Guess a number generated by the computer the fastest</li>
        <li>Remember as many words as possible in seconds</li>
        <li>Resolve 3 simple calculations as fast as possible</li>
    </ul>
    <h3>FIRST ROUND</h3>
    <p>GUESS A NUMBER</p>
    <p>The number to guess is between 0 and 100 included</p>
    <p id="find"></p>
    <input type="text" autofocus id="nb">
    <button onclick="findTheNb(document.getElementById('nb').value, randomNb)">Enter</button>
    <!-- the span says "more" or "less" or "nb found" -->
    <span id="clue"></span> 
    <form action="round2.php"><input type="submit" value="Next Round"></form>

    <script type="text/javascript">
        let spanClue = document.getElementById("clue");
        let inputNb = document.getElementById('nb');

        const randomNb = Math.floor(Math.random() * 101); // generate a random number

        document.getElementById("find").textContent = "find : " + randomNb.toString(); // displays the random number to find

        // onclick button > displays if the user found the right number
        function findTheNb(userNb, nbToFind)
        {
            if (userNb == nbToFind) 
            {
               spanClue.textContent = "You are right ! The number is " + nbToFind.toString();
            }
            else if (userNb > nbToFind)
            {
                spanClue.textContent = "less";
            }
            else
            {
                spanClue.textContent = "more";
            }
        }

        // keydown enter > displays if the user found the right number
        inputNb.addEventListener('keydown', function(event) 
        {
            if (event.key === 'Enter') 
            {
                if(inputNb.value.length != 0)
                {
                    findTheNb(inputNb.value, randomNb);
                }
            }
        });
    </script>
 </body>
 </html>